apply plugin: 'com.android.library'

group = 'expo.modules.oboeaudio'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

def nativeAudioDir = file("${project.projectDir}/../../../../native-audio").absolutePath.replace('\\', '/')

android {
  namespace "expo.modules.oboeaudio"
  ndkVersion rootProject.ext.has("ndkVersion") ? rootProject.ext.get("ndkVersion") : "27.1.12297006"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
    externalNativeBuild {
      cmake {
        cppFlags "-std=c++17 -fexceptions -frtti"
        arguments "-DANDROID_STL=c++_shared", "-DNATIVE_AUDIO_DIR=${nativeAudioDir}"
      }
    }
  }
  buildFeatures {
    prefab true
  }
  externalNativeBuild {
    cmake {
      path "src/main/cpp/CMakeLists.txt"
      version "3.22.1"
    }
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "com.google.oboe:oboe:1.9.3"
}
